import { ArrowRight, Bot, Check, ChevronRight, FileText, Menu, Search, Sparkles, UserCheck, X, Zap } from 'lucide-react';
import { useState } from 'react';
import { Link } from 'react-router-dom';
import { motion } from 'framer-motion';
import Logo from '../components/Logo';

const features = [
  { icon: FileText, title: 'Proposal Generator', text: 'Turn client briefs into confident, tailored proposals in seconds.' },
  { icon: Search, title: 'Gig SEO Optimizer', text: 'Improve titles, tags, and descriptions with focused marketplace keywords.' },
  { icon: UserCheck, title: 'Profile Analyzer', text: 'Find the strengths and gaps that matter most to prospective clients.' },
];
const benefits = ['Fast AI', 'Professional Results', 'Easy to Use', 'Secure', 'Responsive'];
const reveal = { hidden: { opacity: 0, y: 20 }, show: { opacity: 1, y: 0, transition: { duration: 0.45 } } };

export default function Landing() {
  const [menuOpen, setMenuOpen] = useState(false);
  const closeMenu = () => setMenuOpen(false);
  return <div className="min-h-screen overflow-x-hidden bg-[#090714] text-white">
    <header className="sticky top-0 z-50 border-b border-white/10 bg-[#090714]/70 backdrop-blur-xl">
      <nav className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4 sm:px-8" aria-label="Main navigation">
        <Link to="/" onClick={closeMenu} aria-label="Gigora home"><Logo size="md" showBadge /></Link>
        <div className="hidden items-center gap-7 text-sm font-medium text-slate-300 md:flex"><a href="#features" className="transition hover:text-white">Features</a><a href="#pricing" className="transition hover:text-white">Pricing</a><a href="#about" className="transition hover:text-white">About</a></div>
        <div className="hidden items-center gap-3 md:flex"><Link to="/login" className="inline-flex min-h-11 items-center rounded-xl px-4 text-sm font-bold text-slate-200 transition hover:bg-white/10 hover:text-white">Login</Link><Link to="/signup" className="inline-flex min-h-11 items-center rounded-xl bg-gradient-to-r from-violet-500 to-fuchsia-500 px-5 text-sm font-bold text-white shadow-lg shadow-violet-900/40 transition hover:-translate-y-0.5 hover:shadow-violet-700/40">Get Started</Link></div>
        <button className="inline-flex min-h-11 min-w-11 items-center justify-center rounded-xl border border-white/10 text-white md:hidden" onClick={() => setMenuOpen((value) => !value)} aria-label="Toggle navigation" aria-expanded={menuOpen}>{menuOpen ? <X /> : <Menu />}</button>
      </nav>
      {menuOpen && <div className="border-t border-white/10 bg-[#100c22] px-5 py-4 md:hidden"><div className="mx-auto flex max-w-7xl flex-col gap-2 text-sm font-semibold"><a href="#features" onClick={closeMenu} className="rounded-xl px-4 py-3 hover:bg-white/10">Features</a><a href="#pricing" onClick={closeMenu} className="rounded-xl px-4 py-3 hover:bg-white/10">Pricing</a><a href="#about" onClick={closeMenu} className="rounded-xl px-4 py-3 hover:bg-white/10">About</a><Link to="/login" onClick={closeMenu} className="rounded-xl px-4 py-3 hover:bg-white/10">Login</Link><Link to="/signup" onClick={closeMenu} className="rounded-xl bg-violet-600 px-4 py-3 text-center">Get Started</Link></div></div>}
    </header>

    <main>
      <section className="relative isolate overflow-hidden"><div className="absolute inset-x-0 top-0 -z-10 h-[38rem] bg-[radial-gradient(ellipse_at_top,rgba(124,58,237,0.35),transparent_65%)]" /><div className="mx-auto grid max-w-7xl gap-12 px-5 py-20 sm:px-8 lg:grid-cols-[1.08fr_.92fr] lg:items-center lg:py-32">
        <motion.div initial="hidden" animate="show" variants={{ show: { transition: { staggerChildren: 0.1 } } }}><motion.div variants={reveal} className="inline-flex items-center gap-2 rounded-full border border-violet-400/25 bg-violet-400/10 px-3 py-1.5 text-xs font-bold text-violet-200"><Sparkles className="h-3.5 w-3.5" /> AI-native freelance workspace</motion.div><motion.h1 variants={reveal} className="mt-6 max-w-3xl text-5xl font-black tracking-[-0.05em] text-white sm:text-6xl lg:text-7xl">AI Toolkit <span className="bg-gradient-to-r from-violet-300 via-fuchsia-300 to-pink-300 bg-clip-text text-transparent">For Freelancers</span></motion.h1><motion.p variants={reveal} className="mt-6 max-w-xl text-lg leading-8 text-slate-300">Generate winning proposals, optimize Fiverr gigs, and analyze freelancer profiles—all powered by AI.</motion.p><motion.div variants={reveal} className="mt-8 flex flex-col gap-3 sm:flex-row"><Link to="/signup" className="inline-flex min-h-13 items-center justify-center gap-2 rounded-xl bg-white px-6 font-bold text-slate-900 transition hover:-translate-y-0.5 hover:bg-violet-50">Get Started <ArrowRight className="h-4 w-4" /></Link><Link to="/login" className="inline-flex min-h-13 items-center justify-center rounded-xl border border-white/15 px-6 font-bold text-white transition hover:bg-white/10">Login</Link></motion.div><motion.p variants={reveal} className="mt-5 text-sm text-slate-400">Start with 5 free AI uses every day.</motion.p></motion.div>
        <motion.div initial={{ opacity: 0, scale: 0.96 }} animate={{ opacity: 1, scale: 1 }} transition={{ duration: 0.6, delay: 0.2 }} className="relative mx-auto w-full max-w-xl"><div className="rounded-[2rem] border border-white/15 bg-white/[0.07] p-4 shadow-2xl shadow-violet-950/50 backdrop-blur-xl"><div className="rounded-2xl border border-white/10 bg-[#141025] p-5 sm:p-7"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-violet-300">Gigora AI</p><h2 className="mt-2 text-xl font-bold">Your next best pitch</h2></div><div className="rounded-xl bg-violet-500/20 p-3 text-violet-200"><Bot /></div></div><div className="mt-7 space-y-3"><div className="h-3 w-4/5 rounded-full bg-white/10" /><div className="h-3 w-full rounded-full bg-white/10" /><div className="h-3 w-3/5 rounded-full bg-white/10" /></div><div className="mt-7 grid grid-cols-3 gap-3"><MockStat label="Match" value="92%" /><MockStat label="Tone" value="Pro" /><MockStat label="Time" value="10s" /></div></div></div><div className="absolute -left-5 top-16 rounded-2xl border border-white/15 bg-[#211844]/90 p-3 shadow-xl backdrop-blur"><p className="text-xs text-violet-200">SEO score</p><p className="text-xl font-black">86/100</p></div><div className="absolute -right-4 bottom-8 rounded-2xl border border-white/15 bg-[#211844]/90 p-3 shadow-xl backdrop-blur"><p className="text-xs text-violet-200">Proposal ready</p><p className="text-sm font-bold text-emerald-300">Generated</p></div></motion.div>
      </div></section>

      <section id="features" className="border-y border-white/10 bg-white/[0.025] px-5 py-24 sm:px-8"><SectionHeading eyebrow="Everything you need" title="Purpose-built tools for better freelance work" text="From the first profile impression to the final proposal, Gigora keeps your workflow focused." /><div className="mx-auto mt-12 grid max-w-7xl gap-5 md:grid-cols-3">{features.map(({ icon: Icon, title, text }) => <motion.article whileHover={{ y: -6 }} key={title} className="group rounded-3xl border border-white/10 bg-white/[0.05] p-7 shadow-lg shadow-black/10 transition hover:border-violet-400/35 hover:bg-white/[0.08]"><div className="inline-flex rounded-2xl bg-gradient-to-br from-violet-500 to-fuchsia-500 p-3 text-white shadow-lg shadow-violet-900/40"><Icon className="h-6 w-6" /></div><h3 className="mt-6 text-xl font-bold">{title}</h3><p className="mt-3 leading-7 text-slate-300">{text}</p><span className="mt-6 inline-flex items-center gap-1 text-sm font-bold text-violet-300">Explore tool <ChevronRight className="h-4 w-4 transition group-hover:translate-x-1" /></span></motion.article>)}</div></section>

      <section id="about" className="px-5 py-24 sm:px-8"><SectionHeading eyebrow="How it works" title="Three simple steps to stronger client work" /><div className="mx-auto mt-12 grid max-w-6xl gap-5 md:grid-cols-3">{['Create Account', 'Choose Tool', 'Generate Results'].map((step, index) => <div key={step} className="relative rounded-3xl border border-white/10 bg-[#110d20] p-6"><span className="text-sm font-black text-violet-300">0{index + 1}</span><h3 className="mt-6 text-xl font-bold">{step}</h3><p className="mt-2 text-slate-300">{index === 0 ? 'Set up your workspace in moments.' : index === 1 ? 'Pick the AI assistant for the job.' : 'Use clear, polished output with confidence.'}</p>{index < 2 && <ArrowRight className="absolute -right-8 top-1/2 hidden h-6 w-6 text-violet-300 md:block" />}</div>)}</div></section>

      <section className="px-5 pb-24 sm:px-8"><div className="mx-auto max-w-7xl rounded-[2rem] border border-white/10 bg-gradient-to-br from-violet-950/60 to-[#141025] p-7 sm:p-10"><SectionHeading eyebrow="Why Gigora" title="More clarity. Less busywork." /><div className="mt-10 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{benefits.map((benefit) => <div key={benefit} className="rounded-2xl border border-white/10 bg-white/[0.06] p-4 text-sm font-bold text-slate-100"><Check className="mb-3 h-5 w-5 text-violet-300" />{benefit}</div>)}</div></div></section>

      <section id="pricing" className="border-y border-white/10 bg-white/[0.025] px-5 py-24 sm:px-8"><SectionHeading eyebrow="Simple pricing" title="Start free. Upgrade when you grow." text="Everything you need to build a more confident freelance workflow." /><div className="mx-auto mt-12 grid max-w-4xl gap-5 md:grid-cols-2"><PricingCard title="Free" price="Free" detail="5 uses/day" items={['Proposal generation', 'SEO suggestions', 'Profile analysis']} /><PricingCard pro title="Pro" price="$5" detail="per month · unlimited access" items={['Unlimited AI generations', 'Full history access', 'Priority experience']} /></div></section>

      <section className="px-5 py-24 sm:px-8"><div className="mx-auto max-w-6xl rounded-[2rem] bg-gradient-to-r from-violet-600 to-fuchsia-600 px-7 py-14 text-center shadow-2xl shadow-violet-950/40 sm:px-12"><Zap className="mx-auto h-7 w-7" /><h2 className="mx-auto mt-4 max-w-2xl text-3xl font-black tracking-tight sm:text-5xl">Ready to grow your freelance business?</h2><p className="mx-auto mt-4 max-w-xl text-violet-100">Build more compelling work with an AI toolkit that stays out of your way.</p><Link to="/signup" className="mt-8 inline-flex min-h-13 items-center gap-2 rounded-xl bg-white px-6 font-bold text-violet-700 transition hover:-translate-y-0.5 hover:bg-violet-50">Get Started <ArrowRight className="h-4 w-4" /></Link></div></section>
    </main>
    <footer className="border-t border-white/10 px-5 py-10 sm:px-8"><div className="mx-auto flex max-w-7xl flex-col gap-7 sm:flex-row sm:items-center sm:justify-between"><Logo size="sm" /><div className="flex flex-wrap gap-x-6 gap-y-3 text-sm text-slate-400"><a href="#about" className="hover:text-white">About</a><a href="mailto:privacy@gigora.app" className="hover:text-white">Privacy</a><a href="mailto:hello@gigora.app" className="hover:text-white">Contact</a></div><p className="text-sm text-slate-500">© 2026 Gigora. All rights reserved.</p></div></footer>
  </div>;
}

function MockStat({ label, value }) { return <div className="rounded-xl border border-white/10 bg-white/[0.05] p-3"><p className="text-xs text-slate-400">{label}</p><p className="mt-1 font-bold">{value}</p></div>; }
function SectionHeading({ eyebrow, title, text }) { return <div className="mx-auto max-w-2xl text-center"><p className="text-sm font-bold uppercase tracking-[0.18em] text-violet-300">{eyebrow}</p><h2 className="mt-3 text-3xl font-black tracking-tight text-white sm:text-4xl">{title}</h2>{text && <p className="mt-4 leading-7 text-slate-300">{text}</p>}</div>; }
function PricingCard({ title, price, detail, items, pro = false }) { return <article className={`rounded-3xl p-7 ${pro ? 'border border-violet-300/40 bg-gradient-to-br from-violet-600 to-fuchsia-700 shadow-xl shadow-violet-950/40' : 'border border-white/10 bg-[#110d20]'}`}><p className={`text-sm font-bold ${pro ? 'text-violet-100' : 'text-slate-400'}`}>{title} Plan</p><p className="mt-4 text-4xl font-black text-white">{price}</p><p className={`mt-2 text-sm ${pro ? 'text-violet-100' : 'text-slate-300'}`}>{detail}</p><ul className="mt-7 space-y-3">{items.map((item) => <li key={item} className="flex gap-2 text-sm text-white"><Check className="h-5 w-5 shrink-0 text-violet-200" />{item}</li>)}</ul><Link to="/signup" className={`mt-8 inline-flex min-h-12 w-full items-center justify-center rounded-xl px-5 text-sm font-bold transition ${pro ? 'bg-white text-violet-700 hover:bg-violet-50' : 'bg-white/10 text-white hover:bg-white/15'}`}>{pro ? 'Choose Pro' : 'Start Free'}</Link></article>; }
