import { Eye, EyeOff, Lock, Mail, ShieldCheck } from 'lucide-react';
import { motion } from 'framer-motion';
import { Link, useLocation, useNavigate } from 'react-router-dom';
import { useState } from 'react';
import { supabase } from '../supabaseClient';
import Logo from '../components/Logo';

const redirectUrl = `${window.location.origin}/auth/callback`;

export default function Login() {
  const navigate = useNavigate(); const location = useLocation();
  const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [remember, setRemember] = useState(true); const [show, setShow] = useState(false); const [loading, setLoading] = useState(false); const [message, setMessage] = useState(null);
  const resendVerification = async () => { const { error } = await supabase.auth.resend({ type: 'signup', email, options: { emailRedirectTo: redirectUrl } }); if (error) throw error; setMessage({ type: 'success', text: 'Verification email sent. Please check your inbox.' }); };
  const submit = async (event) => { event.preventDefault(); setLoading(true); setMessage(null); try { const { error } = await supabase.auth.signInWithPassword({ email, password }); if (error) { if (/confirm|verified/i.test(error.message)) { await resendVerification(); return; } throw error; } if (!remember) sessionStorage.setItem('gigora-session', 'temporary'); navigate(location.state?.from || '/dashboard', { replace: true }); } catch (error) { setMessage({ type: 'error', text: error.message || 'Unable to sign in. Please try again.' }); } finally { setLoading(false); } };
  const google = async () => { setMessage(null); const { error } = await supabase.auth.signInWithOAuth({ provider: 'google', options: { redirectTo: redirectUrl } }); if (error) setMessage({ type: 'error', text: error.message }); };
  const reset = async () => { if (!email) return setMessage({ type: 'error', text: 'Enter your email address first.' }); setLoading(true); const { error } = await supabase.auth.resetPasswordForEmail(email, { redirectTo: redirectUrl }); setLoading(false); setMessage(error ? { type: 'error', text: error.message } : { type: 'success', text: 'Password reset email sent. Please check your inbox.' }); };
  return <AuthShell title="Welcome back" subtitle="Sign in to continue building a stronger freelance business."><form onSubmit={submit} className="space-y-5"><Notice message={message} /><Field label="Email address" icon={<Mail />}><input type="email" value={email} onChange={(event) => setEmail(event.target.value)} required autoComplete="email" placeholder="you@example.com" className="auth-input" /></Field><div><div className="mb-2 flex items-center justify-between"><label className="auth-label">Password</label><button type="button" onClick={reset} className="text-xs font-bold text-violet-300 hover:text-white">Forgot password?</button></div><div className="relative"><Lock className="auth-icon" /><input type={show ? 'text' : 'password'} value={password} onChange={(event) => setPassword(event.target.value)} required autoComplete="current-password" placeholder="Enter your password" className="auth-input pl-11 pr-12" /><button type="button" onClick={() => setShow(!show)} className="absolute inset-y-0 right-0 px-4 text-slate-400 hover:text-white" aria-label={show ? 'Hide password' : 'Show password'}>{show ? <EyeOff className="h-5 w-5" /> : <Eye className="h-5 w-5" />}</button></div></div><label className="flex cursor-pointer items-center gap-2 text-sm text-slate-300"><input type="checkbox" checked={remember} onChange={(event) => setRemember(event.target.checked)} className="h-4 w-4 rounded border-slate-500 bg-slate-900 text-violet-500 focus:ring-violet-400" />Remember me</label><button disabled={loading} className="auth-primary">{loading ? 'Signing in…' : 'Login'}</button></form><Divider /><button type="button" onClick={google} className="auth-google"><GoogleMark />Continue with Google</button><p className="mt-7 text-center text-sm text-slate-400">New to Gigora? <Link to="/signup" className="font-bold text-violet-300 hover:text-white">Create an account</Link></p></AuthShell>;
}

export function AuthShell({ title, subtitle, children }) { return <main className="auth-page"><div className="auth-orb auth-orb-one" /><div className="auth-orb auth-orb-two" /><motion.section initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.4 }} className="auth-card"><Link to="/" className="inline-flex"><Logo size="lg" showBadge /></Link><div className="mt-9"><span className="inline-flex items-center gap-2 rounded-full border border-violet-400/25 bg-violet-400/10 px-3 py-1 text-[11px] font-bold uppercase tracking-wider text-violet-200"><ShieldCheck className="h-3.5 w-3.5" />Secure access</span><h1 className="mt-4 text-3xl font-black tracking-tight text-white">{title}</h1><p className="mt-2 text-sm leading-6 text-slate-300">{subtitle}</p></div><div className="mt-8">{children}</div></motion.section></main>; }
export function Field({ label, icon, children }) { return <div><label className="auth-label">{label}</label><div className="relative"><span className="auth-icon">{icon}</span>{children}</div></div>; }
export function Notice({ message }) { return message ? <div role="alert" className={`mb-5 rounded-xl border px-4 py-3 text-sm ${message.type === 'error' ? 'border-rose-400/30 bg-rose-400/10 text-rose-100' : 'border-emerald-400/30 bg-emerald-400/10 text-emerald-100'}`}>{message.text}</div> : null; }
export function Divider() { return <div className="my-6 flex items-center gap-3 text-[11px] font-bold uppercase tracking-widest text-slate-500"><span className="h-px flex-1 bg-white/10" />or<span className="h-px flex-1 bg-white/10" /></div>; }
export function GoogleMark() { return <svg aria-hidden="true" viewBox="0 0 24 24" className="h-5 w-5"><path fill="#EA4335" d="M12 5c1.6 0 3 .6 4.1 1.6l3.1-3.1C17.3 1.7 14.8 1 12 1 7.5 1 3.7 3.6 1.9 7.3l3.7 2.9C6.5 7.2 9 5 12 5z"/><path fill="#4285F4" d="M23.5 12.3c0-.8-.1-1.6-.2-2.3H12v4.5h6.5c-.3 1.5-1.1 2.8-2.4 3.7l3.7 2.9c2.2-2 3.7-5 3.7-8.8z"/><path fill="#FBBC05" d="M5.6 14.8c-.2-.7-.4-1.5-.4-2.3s.2-1.6.4-2.3L1.9 7.3C.7 9.7 0 10.8 0 12s.7 2.3 1.9 4.7l3.7-2.9z"/><path fill="#34A853" d="M12 23c3.2 0 6-1.1 8-3l-3.7-2.9c-1.1.7-2.5 1.2-4.3 1.2-3 0-5.5-2.2-6.4-5.2L1.9 16C3.7 19.7 7.5 23 12 23z"/></svg>; }
