import { Check, Eye, EyeOff, Lock, Mail, User, X } from 'lucide-react';
import { Link, useNavigate } from 'react-router-dom';
import { useState } from 'react';
import { supabase } from '../supabaseClient';
import { AuthShell, Divider, Field, GoogleMark, Notice } from './Login';

const redirectUrl = `${window.location.origin}/auth/callback`;
export default function Signup() {
  const navigate = useNavigate(); const [name, setName] = useState(''); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [show, setShow] = useState(false); const [terms, setTerms] = useState(false); const [loading, setLoading] = useState(false); const [message, setMessage] = useState(null);
  const checks = [{ label: '8+ characters', met: password.length >= 8 }, { label: 'Uppercase letter', met: /[A-Z]/.test(password) }, { label: 'Number', met: /\d/.test(password) }]; const strong = checks.every((item) => item.met);
  const submit = async (event) => { event.preventDefault(); if (!strong) return setMessage({ type: 'error', text: 'Choose a stronger password to continue.' }); if (!terms) return setMessage({ type: 'error', text: 'Please accept the terms to continue.' }); setLoading(true); setMessage(null); const { data, error } = await supabase.auth.signUp({ email, password, options: { data: { full_name: name }, emailRedirectTo: redirectUrl } }); setLoading(false); if (error) return setMessage({ type: 'error', text: error.message }); if (data.session) navigate('/dashboard', { replace: true }); else setMessage({ type: 'success', text: 'Verification email sent. Please check your inbox, then continue to your dashboard.' }); };
  const google = async () => { const { error } = await supabase.auth.signInWithOAuth({ provider: 'google', options: { redirectTo: redirectUrl } }); if (error) setMessage({ type: 'error', text: error.message }); };
  return <AuthShell title="Create your account" subtitle="Start using a calmer, smarter toolkit for freelance growth."><form onSubmit={submit} className="space-y-5"><Notice message={message} /><Field label="Full name" icon={<User />}><input value={name} onChange={(event) => setName(event.target.value)} required autoComplete="name" placeholder="Your name" className="auth-input" /></Field><Field label="Email address" icon={<Mail />}><input type="email" value={email} onChange={(event) => setEmail(event.target.value)} required autoComplete="email" placeholder="you@example.com" className="auth-input" /></Field><div><label className="auth-label">Password</label><div className="relative"><Lock className="auth-icon" /><input type={show ? 'text' : 'password'} value={password} onChange={(event) => setPassword(event.target.value)} required autoComplete="new-password" placeholder="Create a password" className="auth-input pl-11 pr-12" /><button type="button" onClick={() => setShow(!show)} className="absolute inset-y-0 right-0 px-4 text-slate-400 hover:text-white" aria-label={show ? 'Hide password' : 'Show password'}>{show ? <EyeOff className="h-5 w-5" /> : <Eye className="h-5 w-5" />}</button></div><div className="mt-3 grid grid-cols-1 gap-1 text-xs sm:grid-cols-3">{checks.map((item) => <span key={item.label} className={`flex items-center gap-1.5 ${item.met ? 'text-emerald-300' : 'text-slate-500'}`}>{item.met ? <Check className="h-3.5 w-3.5" /> : <X className="h-3.5 w-3.5" />}{item.label}</span>)}</div></div><label className="flex cursor-pointer items-start gap-2 text-sm leading-5 text-slate-300"><input type="checkbox" checked={terms} onChange={(event) => setTerms(event.target.checked)} className="mt-0.5 h-4 w-4 rounded border-slate-500 bg-slate-900 text-violet-500 focus:ring-violet-400" />I agree to Gigora’s terms and privacy policy.</label><button disabled={loading} className="auth-primary">{loading ? 'Creating account…' : 'Create account'}</button></form><Divider /><button type="button" onClick={google} className="auth-google"><GoogleMark />Continue with Google</button><p className="mt-7 text-center text-sm text-slate-400">Already have an account? <Link to="/login" className="font-bold text-violet-300 hover:text-white">Login</Link></p></AuthShell>;
}
